#!/usr/bin/env python3
"""Lightweight backend for the LingmoOS build dashboard.

Serves the frontend (index.html / app.js / style.css) and the data.json
generated by fetch_data.py. Also exposes /api/data as a JSON endpoint.

Usage:
    python server.py            # serves on http://localhost:8000
    PORT=9000 python server.py
"""
import json
import os
from http.server import BaseHTTPRequestHandler, HTTPServer

ROOT = os.path.dirname(os.path.abspath(__file__))
PORT = int(os.environ.get("PORT", "8000"))

STATIC = {
    "/": "index.html",
    "/index.html": "index.html",
    "/app.js": "app.js",
    "/style.css": "style.css",
    "/data.json": "data.json",
}

MIME = {
    ".html": "text/html; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
}

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        path = self.path.split("?")[0]
        if path == "/api/data":
            self._serve_json(os.path.join(ROOT, "data.json"))
            return
        filename = STATIC.get(path)
        if filename is None:
            self.send_error(404)
            return
        ext = os.path.splitext(filename)[1]
        full = os.path.join(ROOT, filename)
        if not os.path.exists(full):
            self.send_error(404)
            return
        with open(full, "rb") as f:
            body = f.read()
        self.send_response(200)
        self.send_header("Content-Type", MIME.get(ext, "application/octet-stream"))
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _serve_json(self, full):
        try:
            with open(full, "rb") as f:
                body = f.read()
        except OSError:
            self.send_error(404)
            return
        self.send_response(200)
        self.send_header("Content-Type", MIME[".json"])
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt, *args):
        print(f"[server] {self.address_string()} - {fmt % args}")

if __name__ == "__main__":
    print(f"LingmoOS build dashboard listening on http://localhost:{PORT}")
    HTTPServer(("", PORT), Handler).serve_forever()
